# Generated by Django 4.0.5 on 2022-06-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jsonapp', '0002_delete_meals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('instructions', models.TextField(max_length=20000)),
                ('images', models.URLField(max_length=200000)),
                ('slug', models.SlugField(default='Ashutosh')),
            ],
        ),
    ]
