# Generated by Django 4.0.4 on 2022-06-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userloggin', '0002_delete_loggin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loggin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
