# Generated by Django 4.0.4 on 2022-05-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='salitation',
            new_name='salutation',
        ),
    ]
