# Generated by Django 4.0.4 on 2022-05-26 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
