# Generated by Django 4.0.4 on 2022-05-27 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_register_app', '0003_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='password',
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register_app.register'),
        ),
    ]
